/*
 * Outgoing file RESTful service
 *
 * The methods are restricted to portal user that have the permission for sending documents. Different API versions work differently - be sure  you know what you're doing, before you set an API version. The portal may define a minimum API version that can't be overridden.  Before you can use the REST API for your portal, you need to accept the DSGVO AVV once. Also, the REST API is currently restricted to customers  that bought a PDFMAILER (non-Pure) license from gotomaxx directly, or are coming from XRechnung.new or ZUGFeRD.new.  If you don't know how to get your personal Bearer token (which is required to call any API method), please contact our technical support.  In case your REST client doesn't support OAuth2 or Bearer token, there are other possibilities for authentication:  - Use basic http authentication with your user credentials - Send a valid session ID as value in the parameter (GET or POST) `__sid` with every request  Please ask our technical staff for instructions how to create a valid session ID that can be used with this REST API.  __NOTE__: Boolean parameter values should be given as `1` (`true`) or `0` (`false`).  __NOTE__: The XRechnung API functionality requires a separate license and user permission.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// PDF upload REST email details response object  Possible status values are:
    /// </summary>
    [DataContract]
    public partial class GotomaxxPdfUploadRestResponseEmail : IEquatable<GotomaxxPdfUploadRestResponseEmail>
    {
        /// <summary>
        /// Email recipient address
        /// </summary>
        /// <value>Email recipient address</value>
        [Required]
        [DataMember(Name="emailRecipient", EmitDefaultValue=false)]
        public string EmailRecipient { get; set; }

        /// <summary>
        /// Does the sent email contain the document as attachment?
        /// </summary>
        /// <value>Does the sent email contain the document as attachment?</value>
        [Required]
        [DataMember(Name="emailAttachment", EmitDefaultValue=false)]
        public bool EmailAttachment { get; set; }


        /// <summary>
        /// Delivery status  - `0`: None - `1`: Waiting for delivery - `2`: Delivery - `3`: Delivered - `4`: Delivery failed
        /// </summary>
        /// <value>Delivery status  - `0`: None - `1`: Waiting for delivery - `2`: Delivery - `3`: Delivered - `4`: Delivery failed</value>
        
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum _0Enum for 0
            /// </summary>
            
            _0Enum = 0,
            
            /// <summary>
            /// Enum _1Enum for 1
            /// </summary>
            
            _1Enum = 1,
            
            /// <summary>
            /// Enum _2Enum for 2
            /// </summary>
            
            _2Enum = 2,
            
            /// <summary>
            /// Enum _3Enum for 3
            /// </summary>
            
            _3Enum = 3,
            
            /// <summary>
            /// Enum _4Enum for 4
            /// </summary>
            
            _4Enum = 4
        }

        /// <summary>
        /// Delivery status  - &#x60;0&#x60;: None - &#x60;1&#x60;: Waiting for delivery - &#x60;2&#x60;: Delivery - &#x60;3&#x60;: Delivered - &#x60;4&#x60;: Delivery failed
        /// </summary>
        /// <value>Delivery status  - &#x60;0&#x60;: None - &#x60;1&#x60;: Waiting for delivery - &#x60;2&#x60;: Delivery - &#x60;3&#x60;: Delivered - &#x60;4&#x60;: Delivery failed</value>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GotomaxxPdfUploadRestResponseEmail {\n");
            sb.Append("  EmailRecipient: ").Append(EmailRecipient).Append("\n");
            sb.Append("  EmailAttachment: ").Append(EmailAttachment).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GotomaxxPdfUploadRestResponseEmail)obj);
        }

        /// <summary>
        /// Returns true if GotomaxxPdfUploadRestResponseEmail instances are equal
        /// </summary>
        /// <param name="other">Instance of GotomaxxPdfUploadRestResponseEmail to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GotomaxxPdfUploadRestResponseEmail other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    EmailRecipient == other.EmailRecipient ||
                    EmailRecipient != null &&
                    EmailRecipient.Equals(other.EmailRecipient)
                ) && 
                (
                    EmailAttachment == other.EmailAttachment ||
                    
                    EmailAttachment.Equals(other.EmailAttachment)
                ) && 
                (
                    Status == other.Status ||
                    
                    Status.Equals(other.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (EmailRecipient != null)
                    hashCode = hashCode * 59 + EmailRecipient.GetHashCode();
                    
                    hashCode = hashCode * 59 + EmailAttachment.GetHashCode();
                    
                    hashCode = hashCode * 59 + Status.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(GotomaxxPdfUploadRestResponseEmail left, GotomaxxPdfUploadRestResponseEmail right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GotomaxxPdfUploadRestResponseEmail left, GotomaxxPdfUploadRestResponseEmail right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
