/*
 * Outgoing file RESTful service
 *
 * The methods are restricted to portal user that have the permission for sending documents. Different API versions work differently - be sure  you know what you're doing, before you set an API version. The portal may define a minimum API version that can't be overridden.  Before you can use the REST API for your portal, you need to accept the DSGVO AVV once. Also, the REST API is currently restricted to customers  that bought a PDFMAILER (non-Pure) license from gotomaxx directly, or are coming from XRechnung.new or ZUGFeRD.new.  If you don't know how to get your personal Bearer token (which is required to call any API method), please contact our technical support.  In case your REST client doesn't support OAuth2 or Bearer token, there are other possibilities for authentication:  - Use basic http authentication with your user credentials - Send a valid session ID as value in the parameter (GET or POST) `__sid` with every request  Please ask our technical staff for instructions how to create a valid session ID that can be used with this REST API.  __NOTE__: Boolean parameter values should be given as `1` (`true`) or `0` (`false`).  __NOTE__: The XRechnung API functionality requires a separate license and user permission.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Document form REST response object (without signature and image fields)
    /// </summary>
    [DataContract]
    public partial class GotomaxxDocumentFormRestResponse : IEquatable<GotomaxxDocumentFormRestResponse>
    {
        /// <summary>
        /// ID
        /// </summary>
        /// <value>ID</value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int Id { get; set; }

        /// <summary>
        /// Form name
        /// </summary>
        /// <value>Form name</value>
        [Required]
        [MinLength(1)]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Number of pages in the PDF form template
        /// </summary>
        /// <value>Number of pages in the PDF form template</value>
        [Required]
        [DataMember(Name="pages", EmitDefaultValue=false)]
        public int Pages { get; set; }


        /// <summary>
        /// The PDF signature standard to use  Available PDF signature standards:  - `0`: None (won't sign the PDF document, which is the default) - `1`: CAdES - `2`: CAdES T (contains one timestamp) - `3`: CAdES C (contains one timestamp) - `4`: PAdES B-B - `5`: PAdES B-T (contains one timestamp) - `6`: PAdES B-LTA (contains two timestamps)
        /// </summary>
        /// <value>The PDF signature standard to use  Available PDF signature standards:  - `0`: None (won't sign the PDF document, which is the default) - `1`: CAdES - `2`: CAdES T (contains one timestamp) - `3`: CAdES C (contains one timestamp) - `4`: PAdES B-B - `5`: PAdES B-T (contains one timestamp) - `6`: PAdES B-LTA (contains two timestamps)</value>
        
        public enum SignatureEnum
        {
            
            /// <summary>
            /// Enum _0Enum for 0
            /// </summary>
            
            _0Enum = 0,
            
            /// <summary>
            /// Enum _1Enum for 1
            /// </summary>
            
            _1Enum = 1,
            
            /// <summary>
            /// Enum _2Enum for 2
            /// </summary>
            
            _2Enum = 2,
            
            /// <summary>
            /// Enum _3Enum for 3
            /// </summary>
            
            _3Enum = 3,
            
            /// <summary>
            /// Enum _4Enum for 4
            /// </summary>
            
            _4Enum = 4,
            
            /// <summary>
            /// Enum _5Enum for 5
            /// </summary>
            
            _5Enum = 5,
            
            /// <summary>
            /// Enum _6Enum for 6
            /// </summary>
            
            _6Enum = 6
        }

        /// <summary>
        /// The PDF signature standard to use  Available PDF signature standards:  - &#x60;0&#x60;: None (won&#39;t sign the PDF document, which is the default) - &#x60;1&#x60;: CAdES - &#x60;2&#x60;: CAdES T (contains one timestamp) - &#x60;3&#x60;: CAdES C (contains one timestamp) - &#x60;4&#x60;: PAdES B-B - &#x60;5&#x60;: PAdES B-T (contains one timestamp) - &#x60;6&#x60;: PAdES B-LTA (contains two timestamps)
        /// </summary>
        /// <value>The PDF signature standard to use  Available PDF signature standards:  - &#x60;0&#x60;: None (won&#39;t sign the PDF document, which is the default) - &#x60;1&#x60;: CAdES - &#x60;2&#x60;: CAdES T (contains one timestamp) - &#x60;3&#x60;: CAdES C (contains one timestamp) - &#x60;4&#x60;: PAdES B-B - &#x60;5&#x60;: PAdES B-T (contains one timestamp) - &#x60;6&#x60;: PAdES B-LTA (contains two timestamps)</value>
        [Required]
        [Range(0, 6)]
        [DataMember(Name="signature", EmitDefaultValue=false)]
        public SignatureEnum Signature { get; set; }

        /// <summary>
        /// Party identification using SMS OTP required before signing?
        /// </summary>
        /// <value>Party identification using SMS OTP required before signing?</value>
        [Required]
        [DataMember(Name="identify", EmitDefaultValue=false)]
        public bool Identify { get; set; }

        /// <summary>
        /// Parties
        /// </summary>
        /// <value>Parties</value>
        [Required]
        [DataMember(Name="parties", EmitDefaultValue=false)]
        public List<GotomaxxDocumentFormPartyRestResponse> Parties { get; set; }

        /// <summary>
        /// Fields
        /// </summary>
        /// <value>Fields</value>
        [Required]
        [DataMember(Name="fields", EmitDefaultValue=false)]
        public List<GotomaxxDocumentFormFieldRestResponse> Fields { get; set; }

        /// <summary>
        /// Pre-defined email recipient addresses
        /// </summary>
        /// <value>Pre-defined email recipient addresses</value>
        [Required]
        [DataMember(Name="recipients", EmitDefaultValue=false)]
        public List<string> Recipients { get; set; }

        /// <summary>
        /// Is valid configured for usage?
        /// </summary>
        /// <value>Is valid configured for usage?</value>
        [Required]
        [DataMember(Name="valid", EmitDefaultValue=false)]
        public bool Valid { get; set; }

        /// <summary>
        /// Error message (if invalid)
        /// </summary>
        /// <value>Error message (if invalid)</value>
        [Required]
        [DataMember(Name="error", EmitDefaultValue=true)]
        public string Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GotomaxxDocumentFormRestResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Pages: ").Append(Pages).Append("\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("  Identify: ").Append(Identify).Append("\n");
            sb.Append("  Parties: ").Append(Parties).Append("\n");
            sb.Append("  Fields: ").Append(Fields).Append("\n");
            sb.Append("  Recipients: ").Append(Recipients).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GotomaxxDocumentFormRestResponse)obj);
        }

        /// <summary>
        /// Returns true if GotomaxxDocumentFormRestResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of GotomaxxDocumentFormRestResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GotomaxxDocumentFormRestResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    
                    Id.Equals(other.Id)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Pages == other.Pages ||
                    
                    Pages.Equals(other.Pages)
                ) && 
                (
                    Signature == other.Signature ||
                    
                    Signature.Equals(other.Signature)
                ) && 
                (
                    Identify == other.Identify ||
                    
                    Identify.Equals(other.Identify)
                ) && 
                (
                    Parties == other.Parties ||
                    Parties != null &&
                    other.Parties != null &&
                    Parties.SequenceEqual(other.Parties)
                ) && 
                (
                    Fields == other.Fields ||
                    Fields != null &&
                    other.Fields != null &&
                    Fields.SequenceEqual(other.Fields)
                ) && 
                (
                    Recipients == other.Recipients ||
                    Recipients != null &&
                    other.Recipients != null &&
                    Recipients.SequenceEqual(other.Recipients)
                ) && 
                (
                    Valid == other.Valid ||
                    
                    Valid.Equals(other.Valid)
                ) && 
                (
                    Error == other.Error ||
                    Error != null &&
                    Error.Equals(other.Error)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    
                    hashCode = hashCode * 59 + Pages.GetHashCode();
                    
                    hashCode = hashCode * 59 + Signature.GetHashCode();
                    
                    hashCode = hashCode * 59 + Identify.GetHashCode();
                    if (Parties != null)
                    hashCode = hashCode * 59 + Parties.GetHashCode();
                    if (Fields != null)
                    hashCode = hashCode * 59 + Fields.GetHashCode();
                    if (Recipients != null)
                    hashCode = hashCode * 59 + Recipients.GetHashCode();
                    
                    hashCode = hashCode * 59 + Valid.GetHashCode();
                    if (Error != null)
                    hashCode = hashCode * 59 + Error.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(GotomaxxDocumentFormRestResponse left, GotomaxxDocumentFormRestResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GotomaxxDocumentFormRestResponse left, GotomaxxDocumentFormRestResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
