/*
 * Outgoing file RESTful service
 *
 * The methods are restricted to portal user that have the permission for sending documents. Different API versions work differently - be sure  you know what you're doing, before you set an API version. The portal may define a minimum API version that can't be overridden.  Before you can use the REST API for your portal, you need to accept the DSGVO AVV once. Also, the REST API is currently restricted to customers  that bought a PDFMAILER (non-Pure) license from gotomaxx directly, or are coming from XRechnung.new or ZUGFeRD.new.  If you don't know how to get your personal Bearer token (which is required to call any API method), please contact our technical support.  In case your REST client doesn't support OAuth2 or Bearer token, there are other possibilities for authentication:  - Use basic http authentication with your user credentials - Send a valid session ID as value in the parameter (GET or POST) `__sid` with every request  Please ask our technical staff for instructions how to create a valid session ID that can be used with this REST API.  __NOTE__: Boolean parameter values should be given as `1` (`true`) or `0` (`false`).  __NOTE__: The XRechnung API functionality requires a separate license and user permission.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// JSON document summary object template for documentation purposes and XML transformation
    /// </summary>
    [DataContract]
    public partial class GotomaxxJsonDocumentSummary : IEquatable<GotomaxxJsonDocumentSummary>
    {
        /// <summary>
        /// Line total amount (BT-106)  &#x3D; SUM(ITEMS[TOTAL])  __NOTE__: Actually this value is required, but may be auto-completed from the items.
        /// </summary>
        /// <value>Line total amount (BT-106)  &#x3D; SUM(ITEMS[TOTAL])  __NOTE__: Actually this value is required, but may be auto-completed from the items.</value>
        [DataMember(Name="total", EmitDefaultValue=false)]
        public decimal Total { get; set; }

        /// <summary>
        /// Net amount (BT-109)  &#x3D; SUM(VAT[AMOUNT])  __NOTE__: Actually this value is required, but may be auto-completed from the VAT.
        /// </summary>
        /// <value>Net amount (BT-109)  &#x3D; SUM(VAT[AMOUNT])  __NOTE__: Actually this value is required, but may be auto-completed from the VAT.</value>
        [DataMember(Name="net", EmitDefaultValue=false)]
        public decimal Net { get; set; }

        /// <summary>
        /// Tax amount (BT-110)  &#x3D; SUM(VAT[VATAMOUNT])  __NOTE__: Actually this value is required, but may be auto-completed from the VAT.
        /// </summary>
        /// <value>Tax amount (BT-110)  &#x3D; SUM(VAT[VATAMOUNT])  __NOTE__: Actually this value is required, but may be auto-completed from the VAT.</value>
        [DataMember(Name="tax", EmitDefaultValue=false)]
        public decimal Tax { get; set; }

        /// <summary>
        /// Gross amount (BT-112)  &#x3D; NET + TAX  __NOTE__: Actually this value is required, but may be auto-completed from the VAT.
        /// </summary>
        /// <value>Gross amount (BT-112)  &#x3D; NET + TAX  __NOTE__: Actually this value is required, but may be auto-completed from the VAT.</value>
        [DataMember(Name="gross", EmitDefaultValue=false)]
        public decimal Gross { get; set; }

        /// <summary>
        /// Charge amount (BT-108)  &#x3D; SUM(CHARGE[AMOUNT])  __NOTE__: Actually this value is required, but may be auto-completed from the allowance charge.
        /// </summary>
        /// <value>Charge amount (BT-108)  &#x3D; SUM(CHARGE[AMOUNT])  __NOTE__: Actually this value is required, but may be auto-completed from the allowance charge.</value>
        [DataMember(Name="charge", EmitDefaultValue=false)]
        public decimal Charge { get; set; }

        /// <summary>
        /// Allowance amount (BT-107)  &#x3D; SUM(ALLOWANCE[AMOUNT])  __NOTE__: Actually this value is required, but may be auto-completed from the allowance charge.
        /// </summary>
        /// <value>Allowance amount (BT-107)  &#x3D; SUM(ALLOWANCE[AMOUNT])  __NOTE__: Actually this value is required, but may be auto-completed from the allowance charge.</value>
        [DataMember(Name="allowance", EmitDefaultValue=false)]
        public decimal Allowance { get; set; }

        /// <summary>
        /// Prepaid amount (BT-113)
        /// </summary>
        /// <value>Prepaid amount (BT-113)</value>
        [DataMember(Name="prepaid", EmitDefaultValue=false)]
        public decimal Prepaid { get; set; }

        /// <summary>
        /// Due amount (BT-115)  &#x3D; GROSS - ALLOWANCE + CHARGE - PREPAID  __NOTE__: Actually this value is required, but may be auto-completed from the other values.
        /// </summary>
        /// <value>Due amount (BT-115)  &#x3D; GROSS - ALLOWANCE + CHARGE - PREPAID  __NOTE__: Actually this value is required, but may be auto-completed from the other values.</value>
        [DataMember(Name="due", EmitDefaultValue=false)]
        public decimal Due { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GotomaxxJsonDocumentSummary {\n");
            sb.Append("  Total: ").Append(Total).Append("\n");
            sb.Append("  Net: ").Append(Net).Append("\n");
            sb.Append("  Tax: ").Append(Tax).Append("\n");
            sb.Append("  Gross: ").Append(Gross).Append("\n");
            sb.Append("  Charge: ").Append(Charge).Append("\n");
            sb.Append("  Allowance: ").Append(Allowance).Append("\n");
            sb.Append("  Prepaid: ").Append(Prepaid).Append("\n");
            sb.Append("  Due: ").Append(Due).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GotomaxxJsonDocumentSummary)obj);
        }

        /// <summary>
        /// Returns true if GotomaxxJsonDocumentSummary instances are equal
        /// </summary>
        /// <param name="other">Instance of GotomaxxJsonDocumentSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GotomaxxJsonDocumentSummary other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Total == other.Total ||
                    
                    Total.Equals(other.Total)
                ) && 
                (
                    Net == other.Net ||
                    
                    Net.Equals(other.Net)
                ) && 
                (
                    Tax == other.Tax ||
                    
                    Tax.Equals(other.Tax)
                ) && 
                (
                    Gross == other.Gross ||
                    
                    Gross.Equals(other.Gross)
                ) && 
                (
                    Charge == other.Charge ||
                    
                    Charge.Equals(other.Charge)
                ) && 
                (
                    Allowance == other.Allowance ||
                    
                    Allowance.Equals(other.Allowance)
                ) && 
                (
                    Prepaid == other.Prepaid ||
                    
                    Prepaid.Equals(other.Prepaid)
                ) && 
                (
                    Due == other.Due ||
                    
                    Due.Equals(other.Due)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Total.GetHashCode();
                    
                    hashCode = hashCode * 59 + Net.GetHashCode();
                    
                    hashCode = hashCode * 59 + Tax.GetHashCode();
                    
                    hashCode = hashCode * 59 + Gross.GetHashCode();
                    
                    hashCode = hashCode * 59 + Charge.GetHashCode();
                    
                    hashCode = hashCode * 59 + Allowance.GetHashCode();
                    
                    hashCode = hashCode * 59 + Prepaid.GetHashCode();
                    
                    hashCode = hashCode * 59 + Due.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(GotomaxxJsonDocumentSummary left, GotomaxxJsonDocumentSummary right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GotomaxxJsonDocumentSummary left, GotomaxxJsonDocumentSummary right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
