/*
 * Outgoing file RESTful service
 *
 * The methods are restricted to portal user that have the permission for sending documents. Different API versions work differently - be sure  you know what you're doing, before you set an API version. The portal may define a minimum API version that can't be overridden.  Before you can use the REST API for your portal, you need to accept the DSGVO AVV once. Also, the REST API is currently restricted to customers  that bought a PDFMAILER (non-Pure) license from gotomaxx directly, or are coming from XRechnung.new or ZUGFeRD.new.  If you don't know how to get your personal Bearer token (which is required to call any API method), please contact our technical support.  In case your REST client doesn't support OAuth2 or Bearer token, there are other possibilities for authentication:  - Use basic http authentication with your user credentials - Send a valid session ID as value in the parameter (GET or POST) `__sid` with every request  Please ask our technical staff for instructions how to create a valid session ID that can be used with this REST API.  __NOTE__: Boolean parameter values should be given as `1` (`true`) or `0` (`false`).  __NOTE__: The XRechnung API functionality requires a separate license and user permission.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// JSON document allowance charge object template for documentation purposes and XML transformation
    /// </summary>
    [DataContract]
    public partial class GotomaxxJsonDocumentAllowance : IEquatable<GotomaxxJsonDocumentAllowance>
    {

        /// <summary>
        /// Type
        /// </summary>
        /// <value>Type</value>
        [TypeConverter(typeof(CustomEnumConverter<TypeEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum TypeEnum
        {
            
            /// <summary>
            /// Enum CHARGEEnum for CHARGE
            /// </summary>
            [EnumMember(Value = "CHARGE")]
            CHARGEEnum = 1,
            
            /// <summary>
            /// Enum ALLOWANCEEnum for ALLOWANCE
            /// </summary>
            [EnumMember(Value = "ALLOWANCE")]
            ALLOWANCEEnum = 2
        }

        /// <summary>
        /// Type
        /// </summary>
        /// <value>Type</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum Type { get; set; }

        /// <summary>
        /// Charge net amount (BT-92)
        /// </summary>
        /// <value>Charge net amount (BT-92)</value>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Reason (BT-97)
        /// </summary>
        /// <value>Reason (BT-97)</value>
        [Required]
        [MinLength(1)]
        [DataMember(Name="reason", EmitDefaultValue=false)]
        public string Reason { get; set; }

        /// <summary>
        /// VAT percent (BT-96)  __NOTE__: Actually this value is required, but may be auto-completed from the first VAT record that matches the VAT category.
        /// </summary>
        /// <value>VAT percent (BT-96)  __NOTE__: Actually this value is required, but may be auto-completed from the first VAT record that matches the VAT category.</value>
        [DataMember(Name="vat", EmitDefaultValue=false)]
        public decimal Vat { get; set; }


        /// <summary>
        /// VAT category (BT-95)  - `S`: Default - `Z`: Item without tax - `E`: Exempted from tax - `AE`: Reversal of tax liability - `K`: Exemption from VAT for intra-EEA supply of goods and services - `G`: Free export position, without tax - `O`: Non-tax services - `L`: Canary Islands general indirect tax - `M`: Tax on production, services and imports in Ceuta and Melilla  __NOTE__: Actually this value is required, but may be auto-completed from the first VAT record that matches the VAT.
        /// </summary>
        /// <value>VAT category (BT-95)  - `S`: Default - `Z`: Item without tax - `E`: Exempted from tax - `AE`: Reversal of tax liability - `K`: Exemption from VAT for intra-EEA supply of goods and services - `G`: Free export position, without tax - `O`: Non-tax services - `L`: Canary Islands general indirect tax - `M`: Tax on production, services and imports in Ceuta and Melilla  __NOTE__: Actually this value is required, but may be auto-completed from the first VAT record that matches the VAT.</value>
        [TypeConverter(typeof(CustomEnumConverter<VatCategoryEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum VatCategoryEnum
        {
            
            /// <summary>
            /// Enum SEnum for S
            /// </summary>
            [EnumMember(Value = "S")]
            SEnum = 1,
            
            /// <summary>
            /// Enum ZEnum for Z
            /// </summary>
            [EnumMember(Value = "Z")]
            ZEnum = 2,
            
            /// <summary>
            /// Enum EEnum for E
            /// </summary>
            [EnumMember(Value = "E")]
            EEnum = 3,
            
            /// <summary>
            /// Enum AEEnum for AE
            /// </summary>
            [EnumMember(Value = "AE")]
            AEEnum = 4,
            
            /// <summary>
            /// Enum KEnum for K
            /// </summary>
            [EnumMember(Value = "K")]
            KEnum = 5,
            
            /// <summary>
            /// Enum GEnum for G
            /// </summary>
            [EnumMember(Value = "G")]
            GEnum = 6,
            
            /// <summary>
            /// Enum OEnum for O
            /// </summary>
            [EnumMember(Value = "O")]
            OEnum = 7,
            
            /// <summary>
            /// Enum LEnum for L
            /// </summary>
            [EnumMember(Value = "L")]
            LEnum = 8,
            
            /// <summary>
            /// Enum MEnum for M
            /// </summary>
            [EnumMember(Value = "M")]
            MEnum = 9
        }

        /// <summary>
        /// VAT category (BT-95)  - &#x60;S&#x60;: Default - &#x60;Z&#x60;: Item without tax - &#x60;E&#x60;: Exempted from tax - &#x60;AE&#x60;: Reversal of tax liability - &#x60;K&#x60;: Exemption from VAT for intra-EEA supply of goods and services - &#x60;G&#x60;: Free export position, without tax - &#x60;O&#x60;: Non-tax services - &#x60;L&#x60;: Canary Islands general indirect tax - &#x60;M&#x60;: Tax on production, services and imports in Ceuta and Melilla  __NOTE__: Actually this value is required, but may be auto-completed from the first VAT record that matches the VAT.
        /// </summary>
        /// <value>VAT category (BT-95)  - &#x60;S&#x60;: Default - &#x60;Z&#x60;: Item without tax - &#x60;E&#x60;: Exempted from tax - &#x60;AE&#x60;: Reversal of tax liability - &#x60;K&#x60;: Exemption from VAT for intra-EEA supply of goods and services - &#x60;G&#x60;: Free export position, without tax - &#x60;O&#x60;: Non-tax services - &#x60;L&#x60;: Canary Islands general indirect tax - &#x60;M&#x60;: Tax on production, services and imports in Ceuta and Melilla  __NOTE__: Actually this value is required, but may be auto-completed from the first VAT record that matches the VAT.</value>
        [DataMember(Name="vatCategory", EmitDefaultValue=false)]
        public VatCategoryEnum VatCategory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GotomaxxJsonDocumentAllowance {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Vat: ").Append(Vat).Append("\n");
            sb.Append("  VatCategory: ").Append(VatCategory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GotomaxxJsonDocumentAllowance)obj);
        }

        /// <summary>
        /// Returns true if GotomaxxJsonDocumentAllowance instances are equal
        /// </summary>
        /// <param name="other">Instance of GotomaxxJsonDocumentAllowance to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GotomaxxJsonDocumentAllowance other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Type == other.Type ||
                    
                    Type.Equals(other.Type)
                ) && 
                (
                    Amount == other.Amount ||
                    
                    Amount.Equals(other.Amount)
                ) && 
                (
                    Reason == other.Reason ||
                    Reason != null &&
                    Reason.Equals(other.Reason)
                ) && 
                (
                    Vat == other.Vat ||
                    
                    Vat.Equals(other.Vat)
                ) && 
                (
                    VatCategory == other.VatCategory ||
                    
                    VatCategory.Equals(other.VatCategory)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Type.GetHashCode();
                    
                    hashCode = hashCode * 59 + Amount.GetHashCode();
                    if (Reason != null)
                    hashCode = hashCode * 59 + Reason.GetHashCode();
                    
                    hashCode = hashCode * 59 + Vat.GetHashCode();
                    
                    hashCode = hashCode * 59 + VatCategory.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(GotomaxxJsonDocumentAllowance left, GotomaxxJsonDocumentAllowance right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GotomaxxJsonDocumentAllowance left, GotomaxxJsonDocumentAllowance right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
