/*
 * Outgoing file RESTful service
 *
 * The methods are restricted to portal user that have the permission for sending documents. Different API versions work differently - be sure  you know what you're doing, before you set an API version. The portal may define a minimum API version that can't be overridden.  Before you can use the REST API for your portal, you need to accept the DSGVO AVV once. Also, the REST API is currently restricted to customers  that bought a PDFMAILER (non-Pure) license from gotomaxx directly, or are coming from XRechnung.new or ZUGFeRD.new.  If you don't know how to get your personal Bearer token (which is required to call any API method), please contact our technical support.  In case your REST client doesn't support OAuth2 or Bearer token, there are other possibilities for authentication:  - Use basic http authentication with your user credentials - Send a valid session ID as value in the parameter (GET or POST) `__sid` with every request  Please ask our technical staff for instructions how to create a valid session ID that can be used with this REST API.  __NOTE__: Boolean parameter values should be given as `1` (`true`) or `0` (`false`).  __NOTE__: The XRechnung API functionality requires a separate license and user permission.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// PDF upload REST SMS details response object
    /// </summary>
    [DataContract]
    public partial class GotomaxxPdfUploadRestResponseSMS : IEquatable<GotomaxxPdfUploadRestResponseSMS>
    {
        /// <summary>
        /// SMS recipient number
        /// </summary>
        /// <value>SMS recipient number</value>
        [Required]
        [DataMember(Name="smsRecipient", EmitDefaultValue=false)]
        public string SmsRecipient { get; set; }

        /// <summary>
        /// SMS message length
        /// </summary>
        /// <value>SMS message length</value>
        [Required]
        [DataMember(Name="smsLength", EmitDefaultValue=false)]
        public int SmsLength { get; set; }

        /// <summary>
        /// Advertised SMS?
        /// </summary>
        /// <value>Advertised SMS?</value>
        [Required]
        [DataMember(Name="adSms", EmitDefaultValue=false)]
        public bool AdSms { get; set; }


        /// <summary>
        /// Delivery status  Possible status values are:  - `0`: None - `1`: Waiting for delivery - `2`: Delivery - `3`: Delivered - `4`: Delivery failed
        /// </summary>
        /// <value>Delivery status  Possible status values are:  - `0`: None - `1`: Waiting for delivery - `2`: Delivery - `3`: Delivered - `4`: Delivery failed</value>
        
        public enum StatusEnum
        {
            
            /// <summary>
            /// Enum _0Enum for 0
            /// </summary>
            
            _0Enum = 0,
            
            /// <summary>
            /// Enum _1Enum for 1
            /// </summary>
            
            _1Enum = 1,
            
            /// <summary>
            /// Enum _2Enum for 2
            /// </summary>
            
            _2Enum = 2,
            
            /// <summary>
            /// Enum _3Enum for 3
            /// </summary>
            
            _3Enum = 3,
            
            /// <summary>
            /// Enum _4Enum for 4
            /// </summary>
            
            _4Enum = 4
        }

        /// <summary>
        /// Delivery status  Possible status values are:  - &#x60;0&#x60;: None - &#x60;1&#x60;: Waiting for delivery - &#x60;2&#x60;: Delivery - &#x60;3&#x60;: Delivered - &#x60;4&#x60;: Delivery failed
        /// </summary>
        /// <value>Delivery status  Possible status values are:  - &#x60;0&#x60;: None - &#x60;1&#x60;: Waiting for delivery - &#x60;2&#x60;: Delivery - &#x60;3&#x60;: Delivered - &#x60;4&#x60;: Delivery failed</value>
        [Required]
        [DataMember(Name="status", EmitDefaultValue=false)]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GotomaxxPdfUploadRestResponseSMS {\n");
            sb.Append("  SmsRecipient: ").Append(SmsRecipient).Append("\n");
            sb.Append("  SmsLength: ").Append(SmsLength).Append("\n");
            sb.Append("  AdSms: ").Append(AdSms).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GotomaxxPdfUploadRestResponseSMS)obj);
        }

        /// <summary>
        /// Returns true if GotomaxxPdfUploadRestResponseSMS instances are equal
        /// </summary>
        /// <param name="other">Instance of GotomaxxPdfUploadRestResponseSMS to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GotomaxxPdfUploadRestResponseSMS other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    SmsRecipient == other.SmsRecipient ||
                    SmsRecipient != null &&
                    SmsRecipient.Equals(other.SmsRecipient)
                ) && 
                (
                    SmsLength == other.SmsLength ||
                    
                    SmsLength.Equals(other.SmsLength)
                ) && 
                (
                    AdSms == other.AdSms ||
                    
                    AdSms.Equals(other.AdSms)
                ) && 
                (
                    Status == other.Status ||
                    
                    Status.Equals(other.Status)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (SmsRecipient != null)
                    hashCode = hashCode * 59 + SmsRecipient.GetHashCode();
                    
                    hashCode = hashCode * 59 + SmsLength.GetHashCode();
                    
                    hashCode = hashCode * 59 + AdSms.GetHashCode();
                    
                    hashCode = hashCode * 59 + Status.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(GotomaxxPdfUploadRestResponseSMS left, GotomaxxPdfUploadRestResponseSMS right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GotomaxxPdfUploadRestResponseSMS left, GotomaxxPdfUploadRestResponseSMS right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
