/*
 * Outgoing file RESTful service
 *
 * The methods are restricted to portal user that have the permission for sending documents. Different API versions work differently - be sure  you know what you're doing, before you set an API version. The portal may define a minimum API version that can't be overridden.  Before you can use the REST API for your portal, you need to accept the DSGVO AVV once. Also, the REST API is currently restricted to customers  that bought a PDFMAILER (non-Pure) license from gotomaxx directly, or are coming from XRechnung.new or ZUGFeRD.new.  If you don't know how to get your personal Bearer token (which is required to call any API method), please contact our technical support.  In case your REST client doesn't support OAuth2 or Bearer token, there are other possibilities for authentication:  - Use basic http authentication with your user credentials - Send a valid session ID as value in the parameter (GET or POST) `__sid` with every request  Please ask our technical staff for instructions how to create a valid session ID that can be used with this REST API.  __NOTE__: Boolean parameter values should be given as `1` (`true`) or `0` (`false`).  __NOTE__: The XRechnung API functionality requires a separate license and user permission.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Org.OpenAPITools.Converters;

namespace Org.OpenAPITools.Models
{ 
    /// <summary>
    /// Document form party REST response object
    /// </summary>
    [DataContract]
    public partial class GotomaxxDocumentFormPartyRestResponse : IEquatable<GotomaxxDocumentFormPartyRestResponse>
    {
        /// <summary>
        /// ID
        /// </summary>
        /// <value>ID</value>
        [Required]
        [DataMember(Name="id", EmitDefaultValue=false)]
        public int Id { get; set; }

        /// <summary>
        /// Party name
        /// </summary>
        /// <value>Party name</value>
        [Required]
        [MinLength(1)]
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Customer ID
        /// </summary>
        /// <value>Customer ID</value>
        [Required]
        [DataMember(Name="customer", EmitDefaultValue=false)]
        public int Customer { get; set; }

        /// <summary>
        /// Recipient group ID
        /// </summary>
        /// <value>Recipient group ID</value>
        [Required]
        [DataMember(Name="group", EmitDefaultValue=false)]
        public int Group { get; set; }

        /// <summary>
        /// Is internal staff user?
        /// </summary>
        /// <value>Is internal staff user?</value>
        [Required]
        [DataMember(Name="staff", EmitDefaultValue=false)]
        public bool Staff { get; set; }

        /// <summary>
        /// Color RGB as 24bit integer
        /// </summary>
        /// <value>Color RGB as 24bit integer</value>
        [Required]
        [Range(0, 16777215)]
        [DataMember(Name="color", EmitDefaultValue=false)]
        public int Color { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GotomaxxDocumentFormPartyRestResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Customer: ").Append(Customer).Append("\n");
            sb.Append("  Group: ").Append(Group).Append("\n");
            sb.Append("  Staff: ").Append(Staff).Append("\n");
            sb.Append("  Color: ").Append(Color).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((GotomaxxDocumentFormPartyRestResponse)obj);
        }

        /// <summary>
        /// Returns true if GotomaxxDocumentFormPartyRestResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of GotomaxxDocumentFormPartyRestResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GotomaxxDocumentFormPartyRestResponse other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    
                    Id.Equals(other.Id)
                ) && 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Customer == other.Customer ||
                    
                    Customer.Equals(other.Customer)
                ) && 
                (
                    Group == other.Group ||
                    
                    Group.Equals(other.Group)
                ) && 
                (
                    Staff == other.Staff ||
                    
                    Staff.Equals(other.Staff)
                ) && 
                (
                    Color == other.Color ||
                    
                    Color.Equals(other.Color)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    
                    hashCode = hashCode * 59 + Customer.GetHashCode();
                    
                    hashCode = hashCode * 59 + Group.GetHashCode();
                    
                    hashCode = hashCode * 59 + Staff.GetHashCode();
                    
                    hashCode = hashCode * 59 + Color.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(GotomaxxDocumentFormPartyRestResponse left, GotomaxxDocumentFormPartyRestResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(GotomaxxDocumentFormPartyRestResponse left, GotomaxxDocumentFormPartyRestResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
